### ISSUE TITLE
Error: Invalid response mode

### ISSUE THREAD

**Issue by michielbdejong** [solid/gitter-solid#10]
```sh
loopy:gitter-solid michiel$ SOLID_IDP=https://solid.community SOLID_USERNAME=solid-auth-cli-test-user SOLID_PASSWORD=123 node gitter-solid.js init solid/test-suite
Target roomm name: solid/test-suite
Logging into gitter ...
You are logged into gitter as: michielbdejong
rooms 78
Target room found: solid/test-suite
targetRoomName 1 solid/test-suite
targetRoomName 2 "solid/test-suite"
@@@@@@ undefined
Single room selected: solid/test-suite
Rooms to do: 1
Log into solid
(node:2086) UnhandledPromiseRejectionWarning: Error: Invalid response mode
    at validateResponseMode (/Users/michiel/gh/solid/gitter-solid/node_modules/@trust/oidc-rp/lib/AuthenticationResponse.js:183:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SolidClient.createSession (/Users/michiel/gh/solid/gitter-solid/node_modules/@solid/cli/src/SolidClient.js:53:21)
    at async SolidClient.login (/Users/michiel/gh/solid/gitter-solid/node_modules/@solid/cli/src/SolidClient.js:31:17)
    at async Object.login (/Users/michiel/gh/solid/gitter-solid/node_modules/solid-auth-cli/src/index.js:69:19)
    at async loadConfig (/Users/michiel/gh/solid/gitter-solid/gitter-solid.js:619:17)
    at async go (/Users/michiel/gh/solid/gitter-solid/gitter-solid.js:787:18)
(node:2086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michielbdejong** [comment]
This is most likely an issue with solid-auth-cli, investigating.

**Comment by michielbdejong** [comment]
I'll see if i can fix this using solid-auth-fetcher
